### ISSUE TITLE
UK backtick incorrect on ⌺ ≢ ⍒⍫

### ISSUE THREAD

**Issue by YsHaNgM** [abrudz/Kbd#3]
Running on Windows 11, V17 UK backtick.
`` ` shift ` ``   outputs `` `¬``  where it should be ⌺

`` ` shift 2 ``  outputs ``≢``     where it should be ⍫

`` ` shift 3``  outputs `` `£``   where it should be⍒

`` ` shift '``   outputs `⍫`   where it should be ≢

**Comment by abrudz** [comment]
Sorry, I completely messed up here. Will fix right now.

**Comment by abrudz** [comment]
OK, try it now. Sorry for the mess.

**Comment by YsHaNgM** [comment]
It works perfect now, thanks.
