### ISSUE TITLE
CompUS installer fails due to missing folder

### ISSUE THREAD

**Issue by rikedyp** [abrudz/Kbd#4]
Error reading from file:
C:\tmp\CompUS\amd64\Comp01.dll. Verify that the file exists and that you can access it.

![image](https://user-images.githubusercontent.com/9338369/142442450-697859d4-611e-49a9-8c75-eb47c9f37ef3.png)

The amd64 folder is named ia64 for some reason.

**Comment by abrudz** [comment]
https://github.com/abrudz/Kbd/releases/tag/v18 has been updated with a new CompUS.zip file
